export const Environment = {
    getCardURL: "https://ckrohv0jme.execute-api.ap-northeast-2.amazonaws.com/default/CardBenefitResult",
    iconDict: {
        인터파크: require('./assets/icons/icon_interpark.png'),
        Hmall: require('./assets/icons/icon_hmall.jpeg'),
        CJ온스타일: require('./assets/icons/icon_cjonstyle.png'),
        롯데홈쇼핑: require('./assets/icons/icon_lottehomeshopping.png'),
        '11번가': require('./assets/icons/icon_11st.png'),
        GS홈쇼핑: require('./assets/icons/icon_gsshop.jpeg'),
        AK몰: require('./assets/icons/icon_akmall.png'),
        'SSG.COM': require('./assets/icons/icon_ssg.png'),
        롯데백화점: require('./assets/icons/icon_lottedepartment.png'),
        SK스토아: require('./assets/icons/icon_skstoa.png'),
        홈앤쇼핑: require('./assets/icons/icon_homeandshopping.png'),
        NS홈쇼핑: require('./assets/icons/icon_nshomeshopping.png'),
        'KT알파 쇼핑': require('./assets/icons/icon_ktalphashopping.png'),
        W쇼핑: require('./assets/icons/icon_wshopping.png'),
    },
    urlDict: {
        인터파크: 'http://m.shop.interpark.com',
        Hmall: 'https://www.hmall.com/m/index.do',
        CJ온스타일: 'https://display.cjonstyle.com',
        롯데홈쇼핑: 'https://m.lotteimall.com',
        '11번가': 'http://m.11st.co.kr',
        GS홈쇼핑: 'http://m.gsshop.com',
        AK몰: 'https://m.akmall.com',
        'SSG.COM': 'http://m.ssg.com',
        롯데백화점: 'https://www.lotteon.com/m/display/main/ellotte?mall_no=2',
        SK스토아: 'http://m.skstoa.com',
        홈앤쇼핑: 'https://m.hnsmall.com',
        NS홈쇼핑: 'https://mw.nsmall.com',
        'KT알파 쇼핑': 'https://m.kshop.co.kr',
        W쇼핑: 'http://m.w-shopping.co.kr',
    },
};
