export const Environment = {
  googleAnalytics: true,
  survey: false,
  appUrl: 'https://play.google.com/store/apps/details?id=com.fugether.halmaeapp',
  keywords: `할인메이트, 쇼핑몰, 카드할인, 즉시할인, 청구할인, 인터파크, Hmall, CJ온스타일, 롯데홈쇼핑, 11번가, 
GS홈쇼핑, AK몰, SSG.COM, 롯데백화점, 현대백화점, 더현대닷컴, SK스토아, 홈앤쇼핑, NS홈쇼핑, KT알파쇼핑, W쇼핑, 티몬, 
롯데카드, 현대카드, 신한카드, 국민카드, 농협카드, 삼성카드, 우리카드, 하나카드, 카카오페이, 스마일페이`,
  exceptMall: ['인터파크'],
  iconDict: {
    인터파크: '/assets/icons/icon_interpark.png',
    Hmall: '/assets/icons/icon_hmall.jpeg',
    CJ온스타일: '/assets/icons/icon_cjonstyle.png',
    롯데홈쇼핑: '/assets/icons/icon_lottehomeshopping.png',
    '11번가': '/assets/icons/icon_11st.png',
    GS홈쇼핑: '/assets/icons/icon_gsshop.jpeg',
    AK몰: '/assets/icons/icon_akmall.png',
    'SSG.COM': '/assets/icons/icon_ssg.png',
    롯데백화점: '/assets/icons/icon_lottedepartment.png',
    현대백화점: '/assets/icons/icon_thehyundai.png',
    SK스토아: '/assets/icons/icon_skstoa.png',
    홈앤쇼핑: '/assets/icons/icon_homeandshopping.png',
    NS홈쇼핑: '/assets/icons/icon_nshomeshopping.png',
    'KT알파 쇼핑': '/assets/icons/icon_ktalphashopping.png',
    W쇼핑: '/assets/icons/icon_wshopping.png',
  },
  imageDict: {
    info: '/assets/images/sale896.png',
    screen01: '/assets/images/screen_20230219_01.png',
    screen02: '/assets/images/screen_20230219_02.png',
    screen03: '/assets/images/screen_20230219_03.png',
    screen04: '/assets/images/screen_20230219_04.png',
  },
  urlDict: {
    인터파크: 'http://m.shop.interpark.com',
    Hmall: 'https://www.hmall.com/m/index.do',
    CJ온스타일: 'https://display.cjonstyle.com',
    롯데홈쇼핑: 'https://m.lotteimall.com',
    '11번가': 'http://m.11st.co.kr',
    GS홈쇼핑: 'http://m.gsshop.com',
    AK몰: 'https://m.akmall.com',
    'SSG.COM': 'http://m.ssg.com',
    롯데백화점: 'https://www.lotteon.com/m/display/main/ellotte?mall_no=2',
    현대백화점: 'https://m.thehyundai.com',
    SK스토아: 'http://m.skstoa.com',
    홈앤쇼핑: 'https://m.hnsmall.com',
    NS홈쇼핑: 'https://mw.nsmall.com',
    'KT알파 쇼핑': 'https://m.kshop.co.kr',
    W쇼핑: 'http://m.w-shopping.co.kr',
  },
  widthSetting: {
    slimWidth: 340,
    normal: {
      logoWidth: 96,
      cardMargin: 0.5,
      mallIconWH: '36',
      mallIconStyle: {marginBottom: 5, borderRadius: 5},
        mallIconCaptionSize: 14,
        mallIconAreaWidth: 100,
        benefitPercentWH: 32,
        benefitPercentFontSize: 16,
        benefitPercentFontWeight: 500,
        benefitPercentSpacing: 1,
        benefitFontSize: 16,
        benefitSpacing: 2,
        arrowIconWidth: 30,
      },
      slim: {
        logoWidth: 72,
        cardMargin: 0.5,
        mallIconWH: '32',
        mallIconStyle: {marginBottom: 5, borderRadius: 5},
        mallIconCaptionSize: 10,
        mallIconAreaWidth: 80,
        benefitPercentWH: 28,
        benefitPercentFontSize: 14,
        benefitPercentFontWeight: 500,
        benefitPercentSpacing: 1,
        benefitFontSize: 14,
        benefitSpacing: 2,
        arrowIconWidth: 22,
      },
  }
};
