export const Environment = {
    getCardURL: 'https://ckrohv0jme.execute-api.ap-northeast-2.amazonaws.com/default/CardBenefitResult',
    iconDict: {
        인터파크: require('./assets/icons/icon_interpark.png'),
        Hmall: require('./assets/icons/icon_hmall.jpeg'),
        CJ온스타일: require('./assets/icons/icon_cjonstyle.png'),
        롯데홈쇼핑: require('./assets/icons/icon_lottehomeshopping.png'),
        '11번가': require('./assets/icons/icon_11st.png'),
        GS홈쇼핑: require('./assets/icons/icon_gsshop.jpeg'),
        AK몰: require('./assets/icons/icon_akmall.png'),
        'SSG.COM': require('./assets/icons/icon_ssg.png'),
        롯데백화점: require('./assets/icons/icon_lottedepartment.png'),
        SK스토아: require('./assets/icons/icon_skstoa.png'),
        홈앤쇼핑: require('./assets/icons/icon_homeandshopping.png'),
        NS홈쇼핑: require('./assets/icons/icon_nshomeshopping.png'),
        'KT알파 쇼핑': require('./assets/icons/icon_ktalphashopping.png'),
        W쇼핑: require('./assets/icons/icon_wshopping.png'),
    },
    imageDict: {
        info: require('./assets/images/sale896.png'),
        screen01: require('./assets/images/screen_0815_01.png'),
        screen02: require('./assets/images/screen_0815_02.png'),
        screen03: require('./assets/images/screen_0815_03.png'),
        screen04: require('./assets/images/screen_0815_04.png'),
    },
    urlDict: {
        인터파크: 'http://m.shop.interpark.com',
        Hmall: 'https://www.hmall.com/m/index.do',
        CJ온스타일: 'https://display.cjonstyle.com',
        롯데홈쇼핑: 'https://m.lotteimall.com',
        '11번가': 'http://m.11st.co.kr',
        GS홈쇼핑: 'http://m.gsshop.com',
        AK몰: 'https://m.akmall.com',
        'SSG.COM': 'http://m.ssg.com',
        롯데백화점: 'https://www.lotteon.com/m/display/main/ellotte?mall_no=2',
        SK스토아: 'http://m.skstoa.com',
        홈앤쇼핑: 'https://m.hnsmall.com',
        NS홈쇼핑: 'https://mw.nsmall.com',
        'KT알파 쇼핑': 'https://m.kshop.co.kr',
        W쇼핑: 'http://m.w-shopping.co.kr',
    },
    widthSetting: {
        slimWidth: 340,
        normal: {
            logoWidth: 96,
            cardMargin: 0.5,
            mallIconWH: '36',
            mallIconStyle: {marginBottom: 5, borderRadius: 5},
            mallIconCaptionSize: 14,
            mallIconAreaWidth: 100,
            benefitPercentWH: 32,
            benefitPercentFontSize: 16,
            benefitPercentFontWeight: 500,
            benefitPercentSpacing: 1,
            benefitFontSize: 16,
            benefitSpacing: 2,
            arrowIconWidth: 30,
        },
        slim: {
            logoWidth: 72,
            cardMargin: 0.5,
            mallIconWH: '32',
            mallIconStyle: {marginBottom: 5, borderRadius: 5},
            mallIconCaptionSize: 10,
            mallIconAreaWidth: 80,
            benefitPercentWH: 28,
            benefitPercentFontSize: 14,
            benefitPercentFontWeight: 500,
            benefitPercentSpacing: 1,
            benefitFontSize: 14,
            benefitSpacing: 2,
            arrowIconWidth: 22,
        },
    }
};
